spring:
  datasource:
    url: jdbc:postgresql://localhost:51394/mydatabase
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
    vectorstore:
      pgvector:
        initialize-schema: false